@startuml

autonumber

participant User as u

participant RP as r

participant "Wallet Frontend" as w

participant "Wallet Backend" as b

u --> r : use

r -> b: get metadata
b -> r: metadata

r -> r: create signed presentation request (client_id,\n nonce, redirect_uri, presentation_definition)

r --> u: signed presentation request 
u --> w: signed presentation request
w -> w: authenticate user
w -> w: authenticate and authorize RP
w --> u: show matching credential(s)
u --> w: select/confirm credential
w -> w: create presentation (credential, key)
alt encrypted response
w -> w: encrypt response (using JARM)
w --> u: encrypted presentation response
u --> r: encrypted presentation response
r -> r: decrypt response
else otherwise
w --> u: presentation response (vp_token, presentation_submission)
u --> r: presentation response (vp_token, presentation_submission)
end
r -> r: validate presentation
r -> r: use presented credential 
@enduml