@startuml

autonumber

participant User as u

participant RP as r

participant "RP Backend" as rb

participant "Wallet Frontend" as w

participant "Wallet Backend" as b

u --> r : use

r -> b: get metadata
activate r
b -> r: metadata

r -> r: create request_uri (client_id,\n nonce, redirect_uri, presentation_definition)
r -> r: create signed presentation request \n(client_id, request_uri)
r -> r: render QR code with signed presentation request


u --> w: scan QR code with signed presentation request
activate w
r -> rb : get presentation response
rb -> r : no response yet
w -> w: authenticate user
w -> w: authenticate and authorize RP
w -> w: fetch presentation request
w --> u: show matching credential(s)
u --> w: select/confirm credential
w -> w: create presentation (credential, key)
w -> rb: presentation response \n(vp_token, presentation_submission)
rb -> w: ok
deactivate w
r -> rb: get presentation response
rb -> r: presentation response \n(vp_token, presentation_submission)
r -> r: validate presentation
r -> r: use presented credential 
@enduml