@startuml
participant User as u
participant RP as r
participant "Wallet" as w

u -> r : access content
r --> w: request presentation
u <--> w : select credential
w -> w : create presentation
w --> r : response vp_token

@enduml