@startuml
participant User as u
participant RP as r
participant "Wallet Frontend" as w
participant "Wallet Backend" as b

u -> r : access content
r --> w: request presentation (incl. wallet attestation)
u --> w : select credential
w -> w : create presentation
w -> b : create signed response (vp_token, app attestation) : JARM response object
note left: https://openid.net/specs/openid-financial-api-jarm.html
b -> b : check app_attestation
b -> b : sign response object
b -> w : signed response (iss, aud, exp, vp_token)
w --> r : signed response (iss, aud, exp, vp_token)
note right: iss identifies wallet provider/service

@enduml